// Package relay is the in-memory routing table for lichess OAuth sign-in.
//
// It holds exactly two short-lived things and never touches the database:
//
//	state -> steamID   registered by an FP-authed client before it opens lichess
//	steamID -> code    stashed when lichess redirects back, claimed once by the client
//
// It deliberately does NOT hold, and must never hold:
//
//	the lichess bearer token   (gamchess never sees one — the client exchanges the code)
//	the PKCE code_verifier     (never leaves the client; it is what makes a relayed
//	                            code low-value: single-use, ~1min TTL, useless alone)
//
// Nothing here is persisted. A restart drops every in-flight sign-in, which is
// correct: the codes would have expired anyway, and there is no reason for an
// OAuth code to survive on disk.
package relay

import (
	"sync"
	"time"
)

type stateEntry struct {
	steamID int64
	expires time.Time
}

type codeEntry struct {
	code    string
	expires time.Time
}

type Store struct {
	mu       sync.Mutex
	stateTTL time.Duration
	codeTTL  time.Duration
	states   map[string]stateEntry
	codes    map[int64]codeEntry

	// now is a field so tests can control expiry without sleeping.
	now func() time.Time
}

func New(stateTTL, codeTTL time.Duration) *Store {
	return &Store{
		stateTTL: stateTTL,
		codeTTL:  codeTTL,
		states:   make(map[string]stateEntry),
		codes:    make(map[int64]codeEntry),
		now:      time.Now,
	}
}

// Begin registers state against an FP-verified steamID. The caller must have
// verified steamID — this package trusts what it is handed.
//
// state is generated by the CLIENT and must be high-entropy. It must never be
// the SteamID: that is public, and an attacker who could predict a victim's
// state could deliver their own code to the victim's client, signing the victim
// into the attacker's lichess account. The caller enforces the entropy floor.
func (s *Store) Begin(state string, steamID int64) {
	s.mu.Lock()
	defer s.mu.Unlock()
	// Sweep on the write path. /begin is the only way to grow states, so this
	// bounds both maps by the number of in-flight sign-ins without needing a
	// janitor goroutine (and without a shutdown story for one).
	s.sweep()
	s.states[state] = stateEntry{steamID: steamID, expires: s.now().Add(s.stateTTL)}
}

// ResolveState consumes state and returns the steamID that registered it.
// Single-use: the entry is deleted whether or not it had expired, so a state
// can never be replayed.
func (s *Store) ResolveState(state string) (int64, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	e, ok := s.states[state]
	if !ok {
		return 0, false
	}
	delete(s.states, state)
	if s.now().After(e.expires) {
		return 0, false
	}
	return e.steamID, true
}

// StashCode parks an OAuth code for a steamID to claim. Last write wins: a
// second sign-in attempt supersedes an abandoned one.
func (s *Store) StashCode(steamID int64, code string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.codes[steamID] = codeEntry{code: code, expires: s.now().Add(s.codeTTL)}
}

// TakeCode returns a steamID's pending code exactly once. Single-use: deleted on
// read, expired or not.
func (s *Store) TakeCode(steamID int64) (string, bool) {
	s.mu.Lock()
	defer s.mu.Unlock()
	e, ok := s.codes[steamID]
	if !ok {
		return "", false
	}
	delete(s.codes, steamID)
	if s.now().After(e.expires) {
		return "", false
	}
	return e.code, true
}

// sweep drops expired entries. Callers must hold the lock.
func (s *Store) sweep() {
	now := s.now()
	for k, v := range s.states {
		if now.After(v.expires) {
			delete(s.states, k)
		}
	}
	for k, v := range s.codes {
		if now.After(v.expires) {
			delete(s.codes, k)
		}
	}
}
